services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    secrets:
      - bot_token
    restart: unless-stopped

secrets:
  bot_token:
    file: bot_token.secret